name: Publish Release
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: snapcore/action-build@v1
      id: build
    - uses: actions/upload-artifact@v3
      with:
        name: snap
        path: ${{ steps.build.outputs.snap }}
    - uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_LOGIN }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: edge
